version: "3"

services:
  cont1:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "cont1"
    ports:
      - "100:80"
  cont2:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "cont2"
    ports:
      - "200:80"
  cont3:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "cont3"
    ports:
      - "300:80"
  cont4:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "cont4"
    ports:
      - "400:80"
  cont5:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "cont5"
    ports:
      - "500:80"

  wildfly:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "wildfly"
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./helloworld/deployments:/opt/jboss/wildfly/standalone/deployments"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"
